sudo: false
language: python

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    # LTS
    - python: "2.7"
      env: TOXENV=py27-django111
    - python: "3.4"
      env: TOXENV=py34-django111

    # Latest
    - python: "3.4"
      env: TOXENV=py34-django20
    - python: "3.5"
      env: TOXENV=py35-django20
    - python: "3.6"
      env: TOXENV=py36-django20

    # Pypy
    - python: "pypy"
      env: TOXENV=pypy2-django111
    - python: "pypy3"
      env: TOXENV=pypy3-django20

    # Linting
    - python: "3.6"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
